--Создание таблиц пользователей
CREATE TABLE IF NOT EXISTS users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    VARCHAR(254) NOT NULL,
    login    VARCHAR(254) NOT NULL,
    name     VARCHAR(254) NOT NULL,
    birthday DATE         NOT NULL
);

--Создание таблицы рейтинга
CREATE TABLE IF NOT EXISTS mpa_rating
(
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(254) NOT NULL UNIQUE

);

INSERT INTO mpa_rating (name) SELECT 'G' WHERE NOT EXISTS (SELECT 1 FROM mpa_rating WHERE name = 'G');
INSERT INTO mpa_rating (name) SELECT 'PG' WHERE NOT EXISTS (SELECT 1 FROM mpa_rating WHERE name = 'PG');
INSERT INTO mpa_rating (name) SELECT 'PG-13' WHERE NOT EXISTS (SELECT 1 FROM mpa_rating WHERE name = 'PG-13');
INSERT INTO mpa_rating (name) SELECT 'R' WHERE NOT EXISTS (SELECT 1 FROM mpa_rating WHERE name = 'R');
INSERT INTO mpa_rating (name) SELECT 'NC-17' WHERE NOT EXISTS (SELECT 1 FROM mpa_rating WHERE name = 'NC-17');

--Создание таблицы фильмов
CREATE TABLE IF NOT EXISTS films
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(254) NOT NULL,
    description    VARCHAR(254) NOT NULL,
    release_date   DATE         NOT NULL,
    duration       INT          NOT NULL,
    mpa_rating_id INT          NOT NULL,
    CONSTRAINT fk_mr_films FOREIGN KEY (mpa_rating_id) REFERENCES mpa_rating (id)
);

--Создание таблицы жанров
CREATE TABLE IF NOT EXISTS genre
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(254) NOT NULL
);



--Создание таблицы жанров фильмов
CREATE TABLE IF NOT EXISTS movie_genre
(
    film_id  BIGINT NOT NULL,
    genre_id BIGINT NOT NULL,
    PRIMARY KEY (film_id, genre_id),
    CONSTRAINT fk_mg_films FOREIGN KEY (film_id) REFERENCES films (id),
    CONSTRAINT fk_mg_genre FOREIGN KEY (genre_id) REFERENCES genre (id)
);

--Создание таблицы друзей
CREATE TABLE IF NOT EXISTS friendships
(
    user_id   BIGINT NOT NULL,
    friend_id BIGINT NOT NULL,
    is_confirmed BOOLEAN NOT NULL,
    PRIMARY KEY (user_id, friend_id),
    CONSTRAINT fk_friendships_users FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_friendships_friends FOREIGN KEY (friend_id) REFERENCES users (id) ON DELETE CASCADE
);

--Создание таблицы лайков фильмов
CREATE TABLE IF NOT EXISTS likes_movies
(
    film_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    PRIMARY KEY (film_id, user_id),
    CONSTRAINT fk_likes_movies_films FOREIGN KEY (film_id) REFERENCES films (id) ON DELETE CASCADE,
    CONSTRAINT fk_likes_movies_users FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
)