--Создание таблиц пользователей
CREATE TABLE IF NOT EXISTS users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    VARCHAR(254) NOT NULL,
    login    VARCHAR(254) NOT NULL,
    name     VARCHAR(254) NOT NULL,
    birthday DATE         NOT NULL
);

--Создание таблицы рейтинга
CREATE TABLE IF NOT EXISTS mpa_rating
(
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(254) NOT NULL UNIQUE

);

--Создание таблицы фильмов
CREATE TABLE IF NOT EXISTS films
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(254)       NOT NULL,
    description   VARCHAR(254)       NOT NULL,
    release_date  DATE               NOT NULL,
    duration      INT                NOT NULL,
    mpa_rating_id INT                NOT NULL,
    rating        DOUBLE DEFAULT 0.0 NOT NULL,
    CONSTRAINT fk_mr_films FOREIGN KEY (mpa_rating_id) REFERENCES mpa_rating (id)
);

--Создание таблицы жанров
CREATE TABLE IF NOT EXISTS genres
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(254) NOT NULL
);


--Создание таблицы жанров фильмов
CREATE TABLE IF NOT EXISTS movie_genres
(
    film_id  BIGINT NOT NULL,
    genre_id BIGINT NOT NULL,
    PRIMARY KEY (film_id, genre_id),
    CONSTRAINT fk_mg_films FOREIGN KEY (film_id) REFERENCES films (id) ON DELETE CASCADE,
    CONSTRAINT fk_mg_genre FOREIGN KEY (genre_id) REFERENCES genres (id) ON DELETE CASCADE
);

--Создание таблицы друзей
CREATE TABLE IF NOT EXISTS friendships
(
    user_id      BIGINT  NOT NULL,
    friend_id    BIGINT  NOT NULL,
    is_confirmed BOOLEAN NOT NULL,
    PRIMARY KEY (user_id, friend_id),
    CONSTRAINT fk_friendships_users FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_friendships_friends FOREIGN KEY (friend_id) REFERENCES users (id) ON DELETE CASCADE
);

--Создание таблицы лайков фильмов
CREATE TABLE IF NOT EXISTS rating_movies
(
    film_id BIGINT  NOT NULL,
    user_id BIGINT  NOT NULL,
    rating  INTEGER NOT NULL,
    PRIMARY KEY (film_id, user_id),
    CONSTRAINT fk_rating_movies_films FOREIGN KEY (film_id) REFERENCES films (id) ON DELETE CASCADE,
    CONSTRAINT fk_rating_movies_users FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_rating_likes_users CHECK (rating BETWEEN 1 AND 10)

);

--Создание таблицы событий
CREATE TABLE IF NOT EXISTS events
(
    event_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp  BIGINT      NOT NULL,
    user_id    BIGINT      NOT NULL,
    event_type VARCHAR(10) NOT NULL,
    operation  VARCHAR(10) NOT NULL,
    entity_id  BIGINT      NOT NULL,

    CONSTRAINT fk_ev_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

--Создание таблицы режиссеров
CREATE TABLE IF NOT EXISTS directors
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(254) NOT NULL
);

--Создание таблицы связи фильмов и режиссеров
CREATE TABLE IF NOT EXISTS film_directors
(
    film_id     BIGINT NOT NULL,
    director_id BIGINT NOT NULL,
    PRIMARY KEY (film_id, director_id),
    CONSTRAINT fk_fd_films FOREIGN KEY (film_id) REFERENCES films (id) ON DELETE CASCADE,
    CONSTRAINT fk_fd_directors FOREIGN KEY (director_id) REFERENCES directors (id) ON DELETE CASCADE
);
--Создание таблицы отзывов
CREATE TABLE IF NOT EXISTS reviews
(
    review_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content     VARCHAR(1000) NOT NULL,
    is_positive BOOLEAN       NOT NULL,
    user_id     BIGINT        NOT NULL,
    film_id     BIGINT        NOT NULL,
    useful      INTEGER       NOT NULL DEFAULT 0,
    CONSTRAINT fk_reviews_users FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_reviews_films FOREIGN KEY (film_id) REFERENCES films (id) ON DELETE CASCADE
);

--Создание таблицы лайков/дизлайков отзывов
CREATE TABLE IF NOT EXISTS review_likes
(
    review_id BIGINT  NOT NULL,
    user_id   BIGINT  NOT NULL,
    is_like   BOOLEAN NOT NULL,
    PRIMARY KEY (review_id, user_id),
    CONSTRAINT fk_review_likes_reviews FOREIGN KEY (review_id) REFERENCES reviews (review_id) ON DELETE CASCADE,
    CONSTRAINT fk_review_likes_users FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);